version: '2'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:80
    networks:
      - angular-network
  
  zap-proxy:
    image: owasp/zap2docker-stable
    command: [
      "zap.sh",
      "-cmd",
      "-autorun",
      "/zap/wrk/zap.yaml"
    ]
    volumes:
      - .:/zap/wrk/:rw
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge